name: Multiple Jobs
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step in job1
        run: echo "Hello from job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step in job2
        run: echo "Hello from job2"
